bind-key C-b last-window
set -g history-limit 10000
set -g mouse off
set -g status-style 'bg=#333333 fg=#5eacd3'

# fix garbage chars on Windows Terminal
# https://github.com/microsoft/terminal/issues/18600
set -g escape-time 500
set -g focus-events off
